### ISSUE TITLE
Error Message "Failed to load bucket" while deploying Serverless application

### ISSUE THREAD

**Issue by tvand** [aws/aws-toolkit-eclipse#125]
After working successfully for some weeks, my serverless application cannot be deployed anymore. The Eclipse plugin shows the follwing error:

![awstoolkiterror](https://user-images.githubusercontent.com/18482561/47070949-a0828800-d1f2-11e8-8c08-62eed17cee9d.png)

I created a new project in the wizard to be sure and it shows the exact same behavior. In the AWS Explorer the leaf for S3 shows "Unable to connect" while all other services work.

There is no additional information in the Eclipse log. Is there any other place to look? How can this be fixed?

Bye, Thomas

**Comment by tvand** [comment]
It seems that the problem has been caused by some incompatibility between the AWS Toolkit and the PMD plugin. Removing PMD has fixed it for now. Please try to verify this.

**Comment by zhangzhx** [comment]
It should be because of the PMD plugin. See this issue https://github.com/aws/aws-sdk-java/issues/1622 for detail. The XMLReader could have a conflict in both plugins which results in this issue.

Closing this issue since you figured the reason. Feel free to reopen it or cut a new one if you have more questions.
