### ISSUE TITLE
Unable to upgrade Toolkit version from 2.3.1 

### ISSUE THREAD

**Issue by mashbekh** [aws/aws-toolkit-eclipse#57]
@fulghum   @david-at-aws 
I am trying to deploy a sample application using beanstalk. I installed AWS Core management tools, AWS deployment tools , AWS data management tools on eclipse. The version of AWS Toolkit for eclipse is 2.3.1. I was unable to create beanstalk environment :

Unable to create new environment: No Solution Stack named '64bit Amazon Linux 2014.09 v1.0.0 running Tomcat 7 Java 7' found. (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue; Request ID: d110a588-cb2b-11e6-9f23-e38f4be429de)

Note :  I am using JDK 1.8 and I set up AWS tomcat server 8.

I understand that that 64bit Amazon Linux 2014.09 v1.0.0 running Tomcat 7 Java 7 is deprecated now and the current one supported is 64bit Amazon Linux 2016.09 v2.4.0 running Tomcat 8 Java 8. This is a new solution stack name. I had not mentioned solution stack name -  "64bit Amazon Linux 2014.09 v1.0.0 running Tomcat 7 Java 7" when creating the beanstalk environment. I think its taking it by default because of AWS toolkit version being 2.3.1. 

 I think it is the version issue with AWS toolkit and I have tried to upgrade seeing docs but in vain. I did read that this issue has been fixed with v2.5 onwards. On eclipse Neon and Luna, I am not able to upgrade AWS toolkit to above 2.3.1 because https://aws.amazon.com/eclipse and  https://aws.amazon.com/eclipse/site.xml is not updated with the same. But I am not really sure if v2.3.1 is the cause of this problem.

So I really need some help using latest version of toolkit and getting the right solution stack.
Any help will be appreciated.
Thanks :)

**Comment by zhangzhx** [comment]
Hey @mashbekh,

Sorry for the slow reply. It is not because of the plugin version. It seems to be a bug in the code as [here](https://github.com/aws/aws-toolkit-eclipse/blob/273b315d00f89360411a73cebe0486be0d43ce1c/com.amazonaws.eclipse.elasticbeanstalk/src/com/amazonaws/eclipse/elasticbeanstalk/solutionstacks/Tomcat8SolutionStacks.java#L32).

When 64bit Amazon Linux running Tomcat 8 Java 8 Solution stack is not found, the toolkit would fall back to the legacy solution stack of Tomcat 7 Java 7. However, the constant configuration for that solution stack is removed from the service and not supported any more.

Thanks for reporting this issue. I don't think we should fall back to the legacy solution stack implicitly. Instead, a default Tomcat 8 Java 8 solution stack might be a better option.

**Comment by zhangzhx** [comment]
This has been fixed in the latest release. Thanks for reporting this issue. Please let us know if you have any other questions or feature requests.
