### ISSUE TITLE
Error "Unable to load class" when trying to create a new lambda java project. 

### ISSUE THREAD

**Issue by kedarchaudhari** [aws/aws-toolkit-eclipse#84]
After following all the instructions under "Import into Eclipse and Set up Development Environment" I tried to create a new lambda java project but got the following error- "The selected wizard could not be started. Reason: Plug-in com.amazonaws.eclipse.lambda was unable to load class com.amazonaws.eclipse.lambda.project.wizard.NewLambdaJavaFunctionProjectWizard"
I am attaching the file with the output of the console. 
[aws-lambda-java-project-console-op.txt](https://github.com/aws/aws-toolkit-eclipse/files/1276179/aws-lambda-java-project-console-op.txt)

**Comment by zhangzhx** [comment]
Hey @kedarchaudhari,

Thanks for reporting this issue. Did you import all the projects after checking out the source code? If so, you need to close the project **[com.amazonaws.eclipse.javasdk](https://github.com/aws/aws-toolkit-eclipse/tree/master/thirdparty/com.amazonaws.eclipse.javasdk)** since it's a third party dependency already in the target platform. The rest of the projects are depending on this bundle and should find it's binary in the target platform instead of the workspace. Sorry I didn't mention that in the **[README](https://github.com/aws/aws-toolkit-eclipse/blob/master/README.md)** file. I will correct the file.

**Comment by zhangzhx** [comment]
Closing this issue due to no response for a long time. Feel free to reopen it if you have more questions.
